### ISSUE TITLE
install it on windows 10 give an error

### ISSUE THREAD

**Issue by adals** [richardanaya/js-wasm#1]
cargo install cargo-webassembly

    Updating crates.io index
  Downloaded cargo-webassembly v0.0.10
  Downloaded 1 crate (16.6 KB) in 2.87s
  Installing cargo-webassembly v0.0.10
  Downloaded aead v0.3.2
  Downloaded aes-gcm v0.8.0
  Downloaded async-executor v1.4.0
  Downloaded arrayref v0.3.6
  Downloaded async-io v1.2.0
  Downloaded async-std v1.7.0
  Downloaded base64 v0.13.0
  Downloaded cache-padded v1.1.1
  Downloaded colored v2.0.0
  Downloaded cookie v0.14.3
  Downloaded ctr v0.6.0
  Downloaded futures-lite v1.11.2
  Downloaded ghash v0.3.0
  Downloaded kv-log-macro v1.0.7
  Downloaded stable_deref_trait v1.2.0
  Downloaded polyval v0.4.2
  Downloaded tinyvec v1.1.0
  Downloaded time v0.2.23
  Downloaded waker-fn v1.1.0
  Downloaded wepoll-sys v3.0.1
  Downloaded async-h1 v2.1.4
  Downloaded async-sse v4.1.0
  Downloaded cc v1.0.65
  Downloaded blake3 v0.3.7
  Downloaded data-encoding v2.3.1
  Downloaded crossbeam-utils v0.8.1
  Downloaded hmac v0.10.1
  Downloaded hmac v0.8.1
  Downloaded route-recognizer v0.2.0
  Downloaded serde_qs v0.7.0
  Downloaded unicode-normalization v0.1.16
  Downloaded async-channel v1.5.1
  Downloaded vec-arena v1.0.0
  Downloaded async-session v2.0.1
  Downloaded bincode v1.3.1
  Downloaded const_fn v0.4.3
  Downloaded event-listener v2.5.1
  Downloaded http-client v6.2.0
  Downloaded syn v1.0.51
  Downloaded http-types v2.8.0
  Downloaded async-task v4.0.3
  Downloaded atomic-waker v1.0.0
  Downloaded cipher v0.2.5
  Downloaded crypto-mac v0.8.0
  Downloaded nb-connect v1.0.2
  Downloaded serde_urlencoded v0.7.0
  Downloaded async-global-executor v1.4.3
  Downloaded aes-soft v0.6.4
  Downloaded byte-pool v0.2.2
  Downloaded fastrand v1.4.0
  Downloaded url_open v0.0.1
  Downloaded aes v0.6.0
  Downloaded tide v0.14.0
  Downloaded async-mutex v1.4.0
  Downloaded crypto-mac v0.10.0
  Downloaded infer v0.2.3
  Downloaded yaml-rust v0.3.5
  Downloaded async-attributes v1.1.1
  Downloaded parking v2.0.0
  Downloaded femme v2.1.1
  Downloaded standback v0.2.13
  Downloaded time-macros-impl v0.1.1
  Downloaded async-trait v0.1.42
  Downloaded constant_time_eq v0.1.5
  Downloaded universal-hash v0.4.0
  Downloaded blocking v1.0.2
  Downloaded polling v2.0.2
  Downloaded time-macros v0.1.1
  Downloaded hkdf v0.10.0
  Downloaded concurrent-queue v1.2.2
  Downloaded 70 crates (4.0 MB) in 16.34s (largest was `http-types` at 1.2 MB)
   Compiling version_check v0.9.2
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.51
   Compiling typenum v1.12.0
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.1
   Compiling winapi v0.3.9
   Compiling serde_derive v1.0.117
   Compiling subtle v2.3.0
   Compiling cc v1.0.65
   Compiling serde v1.0.117
   Compiling futures-core v0.3.8
   Compiling log v0.4.11
   Compiling memchr v2.3.4
   Compiling proc-macro-hack v0.5.19
   Compiling libc v0.2.80
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.5.2
   Compiling cache-padded v1.1.1
   Compiling fastrand v1.4.0
   Compiling pin-project-lite v0.1.11
   Compiling parking v2.0.0
   Compiling futures-io v0.3.8
   Compiling getrandom v0.1.15
   Compiling waker-fn v1.1.0
   Compiling lazy_static v1.4.0
   Compiling matches v0.1.8
   Compiling ryu v1.0.5
   Compiling opaque-debug v0.3.0
   Compiling percent-encoding v2.1.0
   Compiling vec-arena v1.0.0
   Compiling async-task v4.0.3
   Compiling tinyvec_macros v0.1.0
   Compiling event-listener v2.5.1
   Compiling serde_json v1.0.59
   Compiling ppv-lite86 v0.2.10
   Compiling itoa v0.4.6
   Compiling const_fn v0.4.3
   Compiling pin-utils v0.1.0
   Compiling atomic-waker v1.0.0
   Compiling cpuid-bool v0.1.2
   Compiling anyhow v1.0.34
   Compiling slab v0.4.2
   Compiling base64 v0.12.3
   Compiling maybe-uninit v2.0.0
   Compiling data-encoding v2.3.1
   Compiling http-types v2.8.0
   Compiling infer v0.2.3
   Compiling base64 v0.13.0
   Compiling byteorder v1.3.4
   Compiling httparse v1.3.4
   Compiling proc-macro-nested v0.1.6
   Compiling constant_time_eq v0.1.5
   Compiling bitflags v1.2.1
   Compiling stable_deref_trait v1.2.0
   Compiling arrayvec v0.5.2
   Compiling arrayref v0.3.6
   Compiling unicode-width v0.1.8
   Compiling vec_map v0.8.2
   Compiling yaml-rust v0.3.5
   Compiling route-recognizer v0.2.0
   Compiling strsim v0.8.0
   Compiling generic-array v0.14.4
   Compiling standback v0.2.13
   Compiling time v0.2.23
   Compiling cookie v0.14.3
   Compiling crossbeam-utils v0.8.1
   Compiling crossbeam-utils v0.7.2
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling concurrent-queue v1.2.2
   Compiling futures-task v0.3.8
   Compiling unicode-bidi v0.3.4
   Compiling form_urlencoded v1.0.0
   Compiling tinyvec v1.1.0
   Compiling async-mutex v1.4.0
   Compiling wepoll-sys v3.0.1
   Compiling blake3 v0.3.7
   Compiling textwrap v0.11.0
   Compiling async-channel v1.5.1
   Compiling unicode-normalization v0.1.16
   Compiling quote v1.0.7
   Compiling num_cpus v1.13.0
   Compiling futures-lite v1.11.2
   Compiling rand_core v0.5.1
   Compiling kv-log-macro v1.0.7
   Compiling idna v0.2.0
   Compiling crossbeam-queue v0.2.3
   Compiling rand_chacha v0.2.2
   Compiling byte-pool v0.2.2
   Compiling digest v0.9.0
   Compiling cipher v0.2.5
   Compiling universal-hash v0.4.0
   Compiling block-buffer v0.9.0
   Compiling crypto-mac v0.10.0
   Compiling aead v0.3.2
   Compiling crypto-mac v0.8.0
   Compiling async-executor v1.4.0
   Compiling blocking v1.0.2
   Compiling rand v0.7.3
   Compiling polyval v0.4.2
   Compiling aes-soft v0.6.4
   Compiling ctr v0.6.0
   Compiling sha2 v0.9.2
   Compiling hmac v0.10.1
   Compiling hmac v0.8.1
   Compiling nb-connect v1.0.2
   Compiling polling v2.0.2
   Compiling time v0.1.44
   Compiling atty v0.2.14
   Compiling ghash v0.3.0
   Compiling aes v0.6.0
   Compiling hkdf v0.10.0
   Compiling async-io v1.2.0
   Compiling clap v2.33.3
   Compiling colored v2.0.0
   Compiling aes-gcm v0.8.0
   Compiling async-global-executor v1.4.3
   Compiling time-macros-impl v0.1.1
   Compiling thiserror-impl v1.0.22
   Compiling async-attributes v1.1.1
   Compiling pin-project-internal v1.0.2
   Compiling async-trait v0.1.42
   Compiling futures-macro v0.3.8
   Compiling async-std v1.7.0
   Compiling time-macros v0.1.1
   Compiling thiserror v1.0.22
   Compiling pin-project v1.0.2
   Compiling futures-util v0.3.8
   Compiling url v2.2.0
   Compiling serde_urlencoded v0.7.0
   Compiling serde_qs v0.7.0
   Compiling bincode v1.3.1
   Compiling chrono v0.4.19
   Compiling url_open v0.0.1
error[E0433]: failed to resolve: maybe a missing crate `winapi`?
  --> C:\Users\.cargo\registry\src\github.com-1ecc6299db9ec823\url_open-0.0.1\src\lib.rs:39:9
   |
39 |     use winapi::um::shellapi::ShellExecuteA;
   |         ^^^^^^ maybe a missing crate `winapi`?

error[E0425]: cannot find function, tuple struct or tuple variant `ShellExecuteA` in this scope
  --> C:\Users\.cargo\registry\src\github.com-1ecc6299db9ec823\url_open-0.0.1\src\lib.rs:42:9
   |
42 |         ShellExecuteA(
   |         ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SW_SHOWNORMAL` in crate `winapi`
  --> C:\Users\.cargo\registry\src\github.com-1ecc6299db9ec823\url_open-0.0.1\src\lib.rs:48:19
   |
48 |           winapi::SW_SHOWNORMAL);
   |                   ^^^^^^^^^^^^^ not found in `winapi`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `url_open`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-webassembly v0.0.10`, intermediate artifacts can be found at `C:\Users\AppData\Local\Temp\cargo-installRwnW7Y`

Caused by:
  build failed
PS C:\Users>

**Comment by richardanaya** [comment]
Thanks so much for this issue, this url_open library is pesky, hoping to replace it asap

**Comment by richardanaya** [comment]
I replaced `url_open` with `webbrowser` this morning and published! Could you let me know if it works on Win10?
