### ISSUE TITLE
could JS_NULL and JS_UNDEFINED be flipped?

### ISSUE THREAD

**Issue by FrankReh** [richardanaya/js-wasm#10]
The js-wasm.js inserts `undefined` first and `null` second but the js-wasm.h define `JS_NULL` as 0 and `JS_UNDEFINED` as 1.

Seems either the js implementation or the header declaration should be flipped.

**Comment by richardanaya** [comment]
fixed :)

**Comment by FrankReh** [comment]
Same issue in js-wasm/crates/js/src/lib.rs

JS_UNDEFINED is 1.0 while JS_NULLis 0.0.
